# -*- coding: utf-8 -*-
"""calculoIMC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJ4iovR89r9sh-qPQ7X2rLMVf1ioiOtB

Calculadora de IMC en Python
"""

def calcular_imc(peso, altura):
  imc = peso / (altura ** 2)
  return imc

"""Solicitar los datos de entrada por el usuario"""

peso = float(input("Ingresa tu peso en Kilogramos: "))
altura = float(input("Ingresa tu altura en metros: "))

"""Calcular el IMC"""

imc = calcular_imc(peso, altura)
print(imc)